openapi: 3.0.0
info:
  version: 3.0.1
  title: SecretSanta Service
  description: Defines How The Secret Santa Contract Should Behave i.e. new teammate, get all secretsantas

tags:
  - name: getAllSecretSanta
    description: getSecret
paths:
  /secretsanta/getAllSecretSanta/{year}:
    get:
      tags:
        - teammate
      summary: get all secret santas in a given year, assuming that secretsantas have not been selected for that year
      operationId: getAllSecretSanta
      parameters:
        - name: year
          in: path
          description: the year of everyone's secret santa
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: teammates who were selected as secretsantas for a year
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Teammates'
        'default':
          description: unexpected error

  /secretsanta/registerTeammate:
    post:
      summary: Create new teammate and persist data to secretsanta table in postgres
      operationId: registerTeammate
      security: []
      responses:
        '200':
          description: teammates who were selected as secretsantas for a year
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Teammates'
        'default':
          description: unexpected error

components:
  schemas:
    Teammates: # Schema name
      type: array
      items:
        $ref: '#/components/schemas/Teammate'
      properties:
    Teammate:    # Schema name
      type: object
      properties:
        id:
          type: integer
          example: 1          # Property example
        firstName:
          type: string
          example: James  # Property example
        secondName:
          type: string
          example: O'Brien  # Property example
        secretSanta:
          type: string
          example: Tom  # Property example
        yearOfSecretSanta:
          type: integer
          example: 1          # Property example
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/jamesobrien/secretSanta/3.0.0